services:
  - type: web
    name: che-forte
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    envVars:
      - key: YTDLP_COOKIES
        value: "/opt/render/project/src/cookies.txt"
    files:
      - path: /opt/render/project/src/cookies.txt
        source: ./cookies.txt
